### ISSUE TITLE
Random mac ids when not connected to any wifi

### ISSUE THREAD

**Issue by arihantdaga** [ferrithemaker/esp8266-wifi-people-counter#1]
Hello, 
This is a very good project. Thank you for making this. I was using it, but i found a challenge or bug, that whenever my mobile is not connected to any wifi, but it has wifi turned on, it sends randomized mac ids, and it keeps changing.. That way the count of devices just keep increasing even though this is only one device.. 
for example form the log - 
```
NEW MAC WITH GOOD SIGNAL DETECTED: daa1192fc45d
NEW MAC WITH GOOD SIGNAL DETECTED: daa11982b699
NEW MAC WITH GOOD SIGNAL DETECTED: daa119010ec2
NEW MAC WITH GOOD SIGNAL DETECTED: daa119af6115
NEW MAC WITH GOOD SIGNAL DETECTED: daa1197e1dd1
...
There is actually only one device. But we are receiving so many new mac ids

```

Can you help me with something here...

**Comment by ferrithemaker** [comment]
Hi! First of all, thanks for using the project! It's a little bit weird but I'll investigate this issue and I'll try on my devices. If you try a different WiFi device, the same problem happens?

**Comment by ferrithemaker** [comment]
I found the problem. If you are using a recent version of Android, there is a new feature called mac randomization to improve privacy.

https://support.boingo.com/s/article/How-to-Disable-MAC-Randomization-in-Android-10-Android-Q

To solve this, one option is change de code to detect a sequence of mac addresses with the same first half as the same device. I'll improve the code in further versions to allow this as an option.

**Comment by arihantdaga** [comment]
Ok. Thanks for prompt reply. I think that explains.

**Comment by ferrithemaker** [comment]
Now you have a "randomizer mode detection" on the mqtt server side, is not tested but... :)

**Comment by arihantdaga** [comment]
HI @ferrithemaker  Thank you for implementing this, but i think the approach we took to check for the first 3 bytes and considering that if first 3 bytes are similar, it means that it is from a same device is not right. 
Actually all phones (Or most phones i found ) will have the same first three bytes da,a1,19.  Or 02,18,6a.

For reference go to this article
https://www.freecodecamp.org/news/tracking-analyzing-over-200-000-peoples-every-step-at-mit-e736a507ddbf/. There he has mentioned this - 
```
Locally addressed “02:18:6a”, 162,589 occurrences
Locally addressed “ da:a1:19”, 145,707 occurrences
74:da:ea from Texas Instruments, 116,133 occurrences
68:c4:4d from Motorola Mobility, 66,829 occurrences
fc:f1:36 from Samsung, 66,573 occurrences
64:bc:0c from LG, 63,200 occurrences
ac:37:43 from HTC, 60,420 occurrences
ac:bc:32 from Apple, 55,643 occurrences
```

**Comment by arihantdaga** [comment]
So if we use the current approach then it'll detect only one device, even when there are many different devices having random mac ids..

**Comment by ferrithemaker** [comment]
Yes, but.... if you look at the code, it marks as the same mac ONLY if the first 3 bytes appears in the last 15 minutes (you can change the threshold). 

For example, if you go to a shop, it will detect you 1 time, and no more (unless you stay more than 15 min), it's true that meanwhile, you cannot detect different devices with the same first 3 bytes, but 15 min later, it will work again. It's not perfect, but I think it's better than the previous version.

It's strange that one of 200k phones that shares the same 3bytes in the world are in the same spot in a 15 min time window, and if it happens, it's better than detect thousands of "randomized" devices.
