### ISSUE TITLE
Still Committed?

### ISSUE THREAD

**Issue by Waynedejager1** [ferrithemaker/esp8266-wifi-people-counter#2]
Hi Ferran is this project still a work in progress or is it open to testing ? Do you have any hardware schematics or BOM file - what sensing device do we use ( PIR )?

**Comment by ferrithemaker** [comment]
Yes! It's open to testing, I'm working on right now, this project doesn't use PIR sensor, check this: https://www.hackster.io/ferrithemaker/esp8266-wifi-people-counter-8cc40c

**Comment by Waynedejager1** [comment]
Thanks Ferran - i am going to watch the development for a while, hoping it goes well. Need to get my head around the concept of tracking via mac address and the radius / diameter of the 8266 range. I use the mix of 8266/influxdb/grafana in a few other projects and find them great ( thats what drew me in ). Good luck ;-) Interesting concept

**Comment by ferrithemaker** [comment]
Maybe you can try, because you will need to fine tunning some parameters, like the signal intesity (dB), the size of the buffer, the time that the device remembers de MAC address, etc...
